name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - main


env:
  ANSIBLE_HOST_KEY_CHECKING: false

jobs:
  deploy:
    runs-on: amazonlinux-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Ansible
        run: |
          sudo apt-get install -y ansible

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          #ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-private-key: ${{ secrets.ubuntu_SSH_PRIVATE_KEY }}

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory.ini deploy_app.yml \
            --inventory "${{ secrets.EC2_PUBLIC_IP }}," \
            --extra-vars "docker_image=mkurmanalieva/myapp:latest ec2_public_ip=${{ secrets.EC2_PUBLIC_IP }}" \
            --connection ssh
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
