name: Build and Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:


      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: 3.13.4
          channel: 'stable'

      - name: Install Dependencies
        working-directory: web_ui_flutter
        run: flutter pub get

      - name: Build APK
        working-directory: web_ui_flutter
        run: flutter build apk --release

      - name: Authenticate with Firebase
        run: |
          npm install -g firebase-tools
          firebase use --add ${{ secrets.FIREBASE_PROJECT_ALIAS }} --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute web_ui_flutter/build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" \
            --groups testers
