name: Build and Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.4
          channel: 'stable'

      - name: Install Dependencies
        working-directory: web_ui_flutter
        run: flutter pub get

      - name: Build APK
        working-directory: web_ui_flutter
        run: flutter build apk --release

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Change to Firebase Project Directory
        run: cd web_ui_flutter

      - name: Initialize Firebase Project
        run: firebase init

      - name: Authenticate with Firebase
        run: |
          firebase use --add ${{ secrets.FIREBASE_PROJECT_ALIAS }} --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute web_ui_flutter/build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" \
            --groups testers
